version: '3'
services:
  my-postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5999:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: my-base
  my-redis:
    image: redis:7.0.12
    restart: always
    ports:
      - "6379:6379"